Repository uvicgse/project-virtual-team-1, pull requests merged in 2019-06, with the labels that each got.

#79 Issue #66: live-reload function for dropdown list - New feature
  app/misc/repo.ts
  index.html
  stylesheets/styles.css
Labels: Group1, Sprint 2

#83 Issue 24 upgrade angular dependencies
  app/misc/color.ts
  app/misc/git.ts
  index.html
  package-lock.json
  package.json
Labels: Group4, Sprint 2

#82 Issue 71 & 72 : double pull or push crash fix and error handling
  app/misc/authenticate.ts
  app/misc/git.ts
Labels: Group2, Sprint 2

#89 Issue 86 allow user to stash changes
  app/components/filePanel/file.panel.component.html
  app/components/header/header.component.html
  app/misc/git.ts
  assets/stash.jpg
  assets/stash.png
  package-lock.json
Labels: Group4, Sprint 2

#97 Issue 7 Graph won't update after commit
  app/misc/git.ts
  index.js
Labels: Group2, Sprint 2, bug

#94 Issue 6 Display Recent Repositories
  .gitignore
  app/components/addRepository/add.repository.component.html
  app/components/addRepository/add.repository.component.ts
  app/misc/repo.ts
  app/misc/router.ts
Labels: Group2, Sprint 2

#84 Feature 54 view tags on existing commits
  app/misc/graphing.ts
  app/misc/repo.ts
Labels: Group1, Sprint 2

#98 Feature 52 - searching tags
  app/components/header/header.component.html
  app/components/header/header.component.ts
  app/misc/git.ts
  app/misc/repo.ts
Labels: Group1, Sprint 2

#107 issue #106: add the ability to stash untracked files
  app/components/header/header.component.html
  app/misc/git.ts
  package-lock.json
  stylesheets/styles.css
Labels: Group4, Sprint 3

#116 ISSUE#105: Allow user to refresh commit graph when detects local repo changes
  app/components/graphPanel/graph.panel.component.html
  app/components/graphPanel/graph.panel.component.ts
  app/misc/git.ts
  app/misc/graphing.ts
  app/misc/repo.ts
  index.html
  stylesheets/styles.css
Labels: Group1, Sprint 3, enhancement

#118 Feature 56 - delete a tag
  app/misc/repo.ts
Labels: Group1, Sprint 3

#117 Feature 49: Allow user to rename or move a file within a repository (incl. Simple-Git integration)
  README.md
  app/components/diffPanel/diff.panel.component.html
  app/components/diffPanel/diff.panel.component.ts
  app/misc/git.ts
  app/misc/router.ts
  package-lock.json
  package.json
  stylesheets/styles.css
Labels: Group4, Sprint 3, enhancement

#100 Issue 19: OAuth implementation
  app/components/authenticate/authenticate.component.html
  app/components/authenticate/authenticate.component.ts
  app/components/header/header.component.html
  app/components/header/header.component.ts
  app/components/pullRequestPanel/pull.request.panel.component.ts
  app/misc/authenticate.ts
  app/misc/readCredentials.ts
  app/misc/repo.ts
  app/misc/router.ts
  app/misc/storeCredentials.ts
  app/misc/wiki.ts
Labels: Group1, Sprint 3

#131 Issue -70 - recloned master and updated unpushed commits count
  app/components/graphPanel/graph.panel.component.html
  app/components/pullRequestPanel/pull.request.panel.component.html
  app/misc/git.ts
  index.html
  package-lock.json
Labels: Group2, Sprint 3, enhancement

#128 Issue 95 - Add Remote Upstream Repository
  app/components/header/header.component.html
  app/misc/git.ts
  assets/addremote.png
  assets/sync.png
  assets/sync.svg
Labels: Group4, Sprint 3, Sprint 4

#169 Feature 110 rebase ui popup fresh
  app/components/header/header.component.html
  app/components/header/header.component.ts
  app/misc/git.ts
  app/misc/repo.ts
  assets/Rebase.png
  stylesheets/styles.css
Labels: Group2, Sprint 4

#166 Feature 150 highlight commits
  app/misc/git.ts
  app/misc/graphSetup.ts
  app/misc/graphing.ts
  package-lock.json
Labels: Group2, Sprint 4

#164 Feature 125 move or rename any file
  app/components/diffPanel/diff.panel.component.html
  app/components/textEditor/text.editor.component.html
  app/components/textEditor/text.editor.component.ts
  app/misc/git.ts
Labels: Group4, Sprint 4, enhancement

#168 Issue 126 apply/drop stashes
  app/components/filePanel/file.panel.component.html
  app/components/footer/footer.component.html
  app/components/footer/footer.component.ts
  app/components/graphPanel/graph.panel.component.html
  app/components/stashPanel/stash.panel.component.html
  app/components/stashPanel/stash.panel.component.ts
  app/misc/color.ts
  app/misc/dragAndDrop.ts
  app/misc/git.ts
  app/misc/router.ts
  index.html
  stylesheets/styles.css
Labels: Group4

#134 Issue 96 - Sync from Fork
  app/components/header/header.component.html
  app/misc/git.ts
Labels: Group4, Sprint 3, Sprint 4

#154 updated the git signatures to the user who is logged in instead of th…
  app/misc/authenticate.ts
  app/misc/git.ts
Labels: Group1, Sprint 4

#162 Issue 132 and 133 - Show and Delete Upstream Repository
  app/components/header/header.component.html
  app/misc/git.ts
  stylesheets/styles.css
Labels: Group4, Sprint 4

#167 Navbar redesign
  app/components/header/header.component.html
  app/misc/authenticate.ts
  package-lock.json
  package.json
  stylesheets/styles.css
Labels: Group4, Sprint 4

#188 Feature 182 move file editor and issues buttons to Navbar
  app/components/footer/footer.component.html
  app/components/footer/footer.component.ts
  app/components/header/header.component.html
  app/components/header/header.component.ts
  app/misc/router.ts
  stylesheets/styles.css
Labels: Group4, Sprint 5

#189 Issue #1 line number repeated in diff file
  app/misc/git.ts
Labels: Sprint 1, Sprint 5

#195 Issue 177 navbar upgrade
  app/components/header/header.component.html
  app/misc/graphing.ts
  index.html
  stylesheets/styles.css
Labels: Group4, Sprint 5

#193 Feature 178 Update Unpushed Commit Highlight Colours
  app/components/pullRequestPanel/pull.request.panel.component.html
  app/misc/authenticate.ts
  package-lock.json
  stylesheets/styles.css
Labels: Group2, Small, Sprint 5, enhancement

#190 UI fixes for issue #171 ,#179 ,#180 ,#187 and feature to undo latest unpush commit.
  app/components/filePanel/file.panel.component.html
  app/components/graphPanel/graph.panel.component.html
  app/components/graphPanel/graph.panel.component.ts
  app/misc/git.ts
  app/misc/graphSetup.ts
  stylesheets/styles.css
Labels: Group2, Sprint 5, bug, enhancement

#194 only show the repo thing and the navbar when there is a repo path
  app/components/addRepository/add.repository.component.html
  app/components/header/header.component.html
  app/misc/router.ts
Labels: Group4, Sprint 5

#198 Fixed issue where user is redirected to the wrong page after logging …
  app/misc/router.ts
Labels: Group1, Sprint 5, Very small, bug

#196 Editing errors for consistency
  app/components/app/app.component.ts
  app/components/textEditor/text.editor.component.ts
  app/misc/authenticate.ts
  app/misc/color.ts
  app/misc/git.ts
  app/misc/graphSetup.ts
  app/misc/graphing.ts
  app/misc/images.ts
  app/misc/repo.ts
  app/misc/router.ts
  app/misc/storeCredentials.ts
  app/misc/wiki.ts
  index.html
Labels: Group1, Sprint 5

#199 Feature 186 drag/drop to commit
  app/components/footer/footer.component.html
  app/components/header/header.component.html
  app/misc/dragAndDrop.ts
  app/misc/git.ts
  app/misc/keyboardShortcuts.ts
  app/misc/router.ts
  index.html
  stylesheets/styles.css
Labels: Group4

#204 Fix "Open in Editor" button in Diff Panel
  app/components/diffPanel/diff.panel.component.ts
Labels: Small, Sprint 5, bug
